<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Refusal Receipt #<?= $data['id'] ?></title>
    <style>
        body {
            font-family: 'Courier New', Courier, monospace;
            background: #f4f4f4;
            display: flex;
            justify-content: center;
            padding: 40px;
        }
        .receipt-container {
            background: white;
            width: 100%;
            max-width: 600px;
            padding: 30px;
            border: 1px solid #ddd;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }
        .header {
            text-align: center;
            border-bottom: 2px dashed #333;
            padding-bottom: 20px;
            margin-bottom: 20px;
        }
        .header h1 { margin: 0; font-size: 22px; text-transform: uppercase; letter-spacing: 2px; }
        .row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 12px;
            font-size: 14px;
        }
        .label { font-weight: bold; color: #555; }
        
        .reason-box {
            margin-top: 20px;
            padding: 15px;
            border: 2px solid #c0392b;
            background: #fff5f5;
            color: #c0392b;
        }
        .reason-title {
            font-weight: bold;
            display: block;
            margin-bottom: 5px;
            text-decoration: underline;
        }
        
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #888;
            border-top: 1px solid #eee;
            padding-top: 15px;
        }
        
        .btn-print {
            display: block;
            width: 100%;
            padding: 15px;
            background: #2c3e50;
            color: white;
            text-align: center;
            text-decoration: none;
            margin-top: 20px;
            border: none;
            cursor: pointer;
            font-family: sans-serif;
            font-weight: bold;
        }
        .btn-print:hover { background: #34495e; }

        @media print {
            body { background: white; padding: 0; }
            .receipt-container { box-shadow: none; border: none; }
            .btn-print { display: none; }
        }
    </style>
</head>
<body>

    <div class="receipt-container">
        <div class="header">
            <h1>Refusal Receipt</h1>
            <p>Official Task Rejection Record</p>
        </div>

        <div class="row">
            <span class="label">Date:</span>
            <span><?= date('Y-m-d H:i') ?></span>
        </div>
        <div class="row">
            <span class="label">Assignment ID:</span>
            <span>#<?= $data['id'] ?></span>
        </div>
        <div class="row">
            <span class="label">Worker Name:</span>
            <span><?= htmlspecialchars($data['worker_name']) ?></span>
        </div>
        <div class="row">
            <span class="label">Worker Role:</span>
            <span><?= ucfirst($data['worker_role']) ?></span>
        </div>

        <hr style="border:0; border-top:1px dashed #ccc; margin:15px 0;">

        <div class="row">
            <span class="label">Order Reference:</span>
            <span><strong>#<?= $data['order_id'] ?></strong></span>
        </div>
        <div class="row">
            <span class="label">Client:</span>
            <span><?= htmlspecialchars($data['client_name']) ?></span>
        </div>
        <div class="row">
            <span class="label">Order Date:</span>
            <span><?= date('Y-m-d', strtotime($data['order_date'])) ?></span>
        </div>

        <div class="reason-box">
            <span class="reason-title">REFUSAL REASON STATED:</span>
            "<?= nl2br(htmlspecialchars($data['refusal_reason'])) ?>"
        </div>

        <div class="footer">
            <p>This document confirms that the assigned task was formally refused by the user.<br>
            System Generated by PLV Manager.</p>
        </div>

        <button onclick="window.print()" class="btn-print">🖨️ Print Receipt / Save as PDF</button>
    </div>

</body>
</html>